name: Create Minor-Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          wget -O /usr/local/bin/semver \
                https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver

      - name: Create Patch Version
        run: |
          git fetch --all --tags
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null)
          test -z "$VERSION" && echo "no version tag found" && VERSION=v0.0.0
          export VERSION=$(semver bump minor $VERSION)
          echo "$VERSION"


      - name: Create Release
        uses: "actions/github-script@v6"
        env:
          VERSION: '${{env.VERSION}}'
        with:
          script: |
            const version = process.env.VERSION
            console.log(version)
            try{
                if (!version || !semver.valid(version)) {
                  throw new Error(`Invalid New Version: ${version}`);
                }
                await github.rest.repos.createRelease({
                  tag_name: version,
                  release_name: version,
                  generate_release_notes: true,
                  draft: false,
                  prerelease: false,
                  make_latest: "false",
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                });
                
                console.log("New Minor-Release Created: " , version , "\n");
                console.log("===================================================");
            }
            catch (error) {
                core.setFailed(error.message);
            }
