name: Create Major-Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          wget -O /usr/local/bin/semver \
                https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver

      - name: Create Major Release
        run: |
          echo "test0"
          semver --version
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          echo "test0"
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null)
          echo "test1"
          test -z "$VERSION" && echo "no version tag found" && VERSION=v0.0.0
          echo "test2"
          VERSION=$(semver bump major $VERSION)
          echo "test3"
          git tag -a $VERSION -m "major release created" HEAD
          echo "test4"
          git push --tags
          echo "test5"
          echo "New Major-Release Created: ${VERSION}"
          git checkout tags/${VERSION}
          git checkout -b release-${VERSION}
          git commit -am "Release ${VERSION}"
          git push origin release-${VERSION}
